version: "3.1"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Toto
      MYSQL_DATABASE: PC_DE_LEO
    volumes:
      - pokedex:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  pokedex: